@isTest
private class nmSapSoapFunctionsMcSTracker
{
    private static testmethod void unit1()
    {
        nmSapSoapFunctionsMcS obj = new nmSapSoapFunctionsMcS();
        nmSapSoapFunctionsMcS.Bapiret2 objB =new nmSapSoapFunctionsMcS.Bapiret2();
        nmSapSoapFunctionsMcS.ZST_CREATE objZ=new nmSapSoapFunctionsMcS.ZST_CREATE();
        nmSapSoapFunctionsMcS.Bapiret2T objB1=new nmSapSoapFunctionsMcS.Bapiret2T();
        nmSapSoapFunctionsMcS.ZstCreateBapi_element  objZE=new nmSapSoapFunctionsMcS.ZstCreateBapi_element();
        nmSapSoapFunctionsMcS.ZstCreateBapiResponse_element objZRE=new nmSapSoapFunctionsMcS.ZstCreateBapiResponse_element();
        nmSapSoapFunctionsMcS.BapistudentPersonal objBSP=new nmSapSoapFunctionsMcS.BapistudentPersonal();
    }

}