public class nmStopRecursion {

    public static Boolean stopRecursivePaymentTriggerRun = false;
    public static Boolean stopRecursiveAccountTriggerRun = false;
    public static Boolean stopRecursiveAccountTriggerRun2 = false;
    public static Boolean stopRecursiveLeadTriggerRun = false;
   // public static Boolean stopRecursiveLinkforDocumentTriggerRun = false;
    public static Boolean stopRecursivePaymentTriggerHandlerRun = false;
    public static Boolean stopRecursiveOpportunityTriggerHandlerRun = false;
    
}