/**
 * @description       : 
 * @author            : @BK
 * @group             : 
 * @last modified on  : 08-08-2024
 * @last modified by  : @BK
**/
public class StudentDetails {
    public String studentName {get;set;}
    public String firstName {get;set;}
    public String lastName {get;set;}
    public String studentEmail {get;set;}
    public String studentMobileNo {get;set;}
    public String studentAddress {get;set;}
    public String studentCity {get;set;}
    public String studentCountry {get;set;}
    public String studentPincode {get;set;}
    public String studentShippingAddress {get;set;}
    public String studentNo {get;set;}
    public String eligibility {get;set;}
    public String studentNumber {get;set;}
    public String programCategory {get;set;}
    public String program {get;set;}
    public String programSpecialisaton {get;set;}
}